name: "Build and maybe publish site"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  ema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build sources & site 🔧
        run: |
          nix build .#site-github -j 4
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: result
          cname: blog.theresa.ai
